const papers = [
  {title:"DanceHMR",date:"2026.05.18",venue:"arXiv 2026",tag:"视频",signal:"手部 + 全身",summary:"把身体上下文与手部局部观测融合到统一时序架构，聚焦单目视频中的全身稳定性与细粒度手势。",href:"https://arxiv.org/abs/2605.18102"},
  {title:"InterMesh",date:"2026.05.06",venue:"arXiv 2026",tag:"多人",signal:"显式交互",summary:"将人—物与人—人交互语义显式注入多人网格恢复，面向遮挡、接触和复杂互动场景。",href:"https://arxiv.org/abs/2605.04554"},
  {title:"Fast SAM 3D Body",date:"2026.03.16",venue:"arXiv 2026",tag:"实时",signal:"最高 10.9×",summary:"以训练无关的并行化与剪枝加速 SAM 3D Body，探索单 RGB 流驱动实时人体控制。",href:"https://arxiv.org/abs/2603.15603"},
  {title:"SAM 3D Body",date:"2026.02.23",venue:"CVPR 2026",tag:"单图",signal:"可提示全身",summary:"可提示的单图全身 HMR 模型，强调复杂野外场景下的泛化、遮挡鲁棒性与统一全身网格。",href:"https://openaccess.thecvf.com/content/CVPR2026/html/Yang_SAM_3D_Body_Robust_Full-Body_Human_Mesh_Recovery_CVPR_2026_paper.html"},
  {title:"Metric-Aware HMR",date:"2025.11.17",venue:"arXiv 2025",tag:"多人",signal:"尺度一致性",summary:"联合优化拥挤场景中所有人的相机空间位置，直接估计具有真实尺度感的网格与相机参数。",href:"https://arxiv.org/abs/2511.13282"},
  {title:"Fish2Mesh Transformer",date:"2025.10",venue:"ICCV 2025",tag:"第一视角",signal:"鱼眼感知",summary:"针对头戴鱼眼相机的畸变与自遮挡，引入第一视角位置编码并回归 SMPL 与相机位移。",href:"https://openaccess.thecvf.com/content/ICCV2025/html/Shen_Fish2Mesh_Transformer_3D_Human_Mesh_Recovery_from_Egocentric_Vision_ICCV_2025_paper.html"},
  {title:"MEGA",date:"2025.06",venue:"CVPR 2025",tag:"生成式",signal:"多解建模",summary:"将姿态与体型离散为 token，以掩码生成建模同时支持确定性单解与随机多解恢复。",href:"https://openaccess.thecvf.com/content/CVPR2025/html/Fiche_MEGA_Masked_Generative_Autoencoder_for_Human_Mesh_Recovery_CVPR_2025_paper.html"},
  {title:"BLADE",date:"2025.06",venue:"CVPR 2025",tag:"单图",signal:"透视校准",summary:"从单图可靠估计深度平移、焦距与完整 3D 位移，改善近距离人体的投影与网格对齐。",href:"https://openaccess.thecvf.com/content/CVPR2025/html/Wang_BLADE_Single-view_Body_Mesh_Estimation_through_Accurate_Depth_Estimation_CVPR_2025_paper.html"},
  {title:"HeatFormer",date:"2025.06",venue:"CVPR 2025",tag:"多视角",signal:"神经优化器",summary:"以热图生成与对齐迭代细化 SMPL 参数，并对相机数量、布置和标定方式保持较强适应性。",href:"https://openaccess.thecvf.com/content/CVPR2025/html/Matsubara_HeatFormer_A_Neural_Optimizer_for_Multiview_Human_Mesh_Recovery_CVPR_2025_paper.html"}
];
const filters=["全部","单图","视频","多人","实时","生成式","多视角"];let active="全部";
const list=document.querySelector("#paper-list"),search=document.querySelector("#paper-search"),filterBox=document.querySelector("#filters");
function renderFilters(){filterBox.innerHTML=filters.map(f=>`<button type="button" class="${f===active?"active":""}" data-filter="${f}">${f}</button>`).join("");}
function render(){const q=search.value.trim().toLowerCase();const visible=papers.filter(p=>(active==="全部"||p.tag===active||(active==="视频"&&p.tag==="第一视角"))&&(!q||Object.values(p).join(" ").toLowerCase().includes(q)));list.innerHTML=visible.length?visible.map((p,i)=>`<a class="paper-row" href="${p.href}" target="_blank" rel="noreferrer"><div class="paper-index">${String(i+1).padStart(2,"0")}</div><div class="paper-main"><div class="paper-topline"><span>${p.venue}</span><time>${p.date}</time></div><h3>${p.title}</h3><p>${p.summary}</p></div><div class="paper-side"><span>${p.tag}</span><b>${p.signal}</b></div><i>↗</i></a>`).join(""):`<div class="empty">没有匹配的论文。试试更短的关键词。</div>`;}
filterBox.addEventListener("click",e=>{if(e.target.matches("button")){active=e.target.dataset.filter;renderFilters();render();}});search.addEventListener("input",render);renderFilters();render();
